services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oilweek-frontend
    restart: unless-stopped
    networks:
      - oilweek-network

networks:
  oilweek-network:
    external: true
